apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout-api
  template:
    metadata:
      labels:
        app: checkout-api
    spec:
      containers:
      - name: checkout-api
        image: nginx:latest
        command: ["/bin/sh", "-c", "exit 1"] # Força o erro na hora de subir
        resources:
          limits:
            memory: "4Mi" # Memória ridiculamente baixa para causar OOM